packages:
<<<<<<< HEAD
  - "apps/*"
  - "packages/*"
=======
    - 'packages/*'
>>>>>>> 6baf4bff09190b89fb5e9a722be32ee4bb97fe72
importers:
    .:
        specifiers:
            turbo: '^2.0.3'
            typescript: '^5.4.5'
            eslint: '^8.2.0'
            prettier: '^3.3.2'
