[entryPoints]
    [entryPoints.web]
        address = ":80"

    [entryPoints.web.http]
        [entryPoints.web.http.redirections]
            [entryPoints.web.http.redirections.entryPoint]
                to = "websecure"
                scheme = "https"
    
    [entryPoints.web.http3]
        advertisedPort = 443

    [entryPoints.websecure]
        address = ":443"

[accessLog]

[api]
dashboard = false

[providers]
  [providers.docker]
    exposedByDefault = false

[certificatesResolvers.letsencrypt.acme]
    email = "example@gmail.com"
    storage = "/certificates/acme.json"
    [certificatesResolvers.letsencrypt.acme.httpChallenge]
        entryPoint = "web"

